### PR TITLE
Update for Atom 1.0

### PR DESCRIPTION
**Pull request by kankaristo**
This pull request updates `branch-status` to work with current versions of Atom. It should also be compatible with Atom 1.0.

The main problem was `keytar`, which wasn't returning an API access token (for reasons unknown to me). There were quite a few deprecations as well, which would have stopped working in Atom 1.0.

The package now uses a personal access token, which the user can give in the package's settings. This is probably better anyway, because the personal access token will be used only for this package, instead of it being a global token used for everything in Atom. If the token is not given in the settings, the package defaults to unauthenticated API requests, which have a rate limit of 60 requests per hour.

The request now uses the `If-None-Match` header, so if the status hasn't changed, the requests don't count towards the GitHub API rate limit. The status is still polled every 5 seconds, but I'm not aware of any way to avoid this.

The package used to only check the latest status, which meant that if the ref had multiple statuses (with different contexts) `branch-status` was showing an incorrect status. This should be working now (I tested this with https://github.com/atom/atom, which has multiple statuses for one ref).

The package also has some nice error handling now. The branch name turns pink if an error occurs, and the error is printed into the console. This happens if the API rate limit is reached, if the branch is not found on GitHub (it could be private), if there was an authentication error, etc.

The package load time was pretty huge (around 300 ms), and I tried to improve that as well. Now the load and activation times are both under 5 ms, but I'm not sure if everything I've done is perfectly kosher...

These are some pretty big changes and I'm a novice when it comes to CoffeeScript, Atom packages and the GitHub API, so this could definitely use a thorough review. :)

This would close https://github.com/nakajima/atom-branch-status/issues/9 and https://github.com/nakajima/atom-branch-status/issues/5.

### CODE REVIEW

**Comment by kankaristo** [comment]
Also, I can't confirm if the pull request link (next to the branch name) is working (due to https://github.com/atom/atom/issues/6335), so someone should check that it works.

**Comment by kankaristo** [comment]
Added a tool tip with the status message (from the first failed/pending/successful status, in that order).

Also added a link to the `target_url` in the status.

**Comment by kankaristo** [comment]
@nakajima, could you take a look at this? I've been using this for a while now, and it seems to be working well.

**Comment by maddox** [comment]
I'm using this branch and having some issues. Even though I put in my API key, it doesn't look like it's working.

I simply put my key in the settings of this package, do I need to do something else?

branch

**Comment by kankaristo** [comment]
Are you using a personal access token (OAuth) or something else? The token needs at least the `repo:status` permission. I've added instructions to [README.md](https://github.com/kankaristo/atom-branch-status/blob/update-for-1.0/README.md).

It's weird that you're getting "API rate limit exceeded", that should only happen for unauthenticated requests (60 requests per hour). The rate limit for authenticated requests is somewhere around 5000 per hour.

If there's something wrong with the token (e.g. if I intentionally remove a character), it should say "Bad credentials" instead.

**Comment by maddox** [comment]
> Are you using a personal access token (OAuth) or something else? The token needs at least the repo:status permission. I've added instructions to README.md.

Yup. I created a fresh new one just for this.

> It's weird that you're getting "API rate limit exceeded", that should only happen for unauthenticated requests (60 requests per hour). The rate limit for authenticated requests is somewhere around 5000 per hour.

I was thinking because there might be an issue when using the token I put into settings. Like maybe it's not actually using it?

> If there's something wrong with the token (e.g. if I intentionally remove a character), it should say "Bad credentials" instead.

Ohhhh. Hmm. Ok. Let me do some more looking around.

**Comment by kankaristo** [comment]
Does changing branches do anything different?

The package uses the `If-None-Match` header to reduce unnecessary requests. It's possible that the GitHub API is responding 304 ("Not Modified") and `branch-status` never clears the error, even though the API request is going through (but returning 304).

This *should* be fixed by changing branches (the URI changes), or at the very least, reloading the package.

You can also see if the request is giving an error (should be printed to the console).

**Comment by maddox** [comment]
Well this is interesting:

In my `Personal access tokens` page in settings:

> Atom Token — gist, repo, user - Never Used

**Comment by maddox** [comment]
Ok, so I was screwing everything up, lol. My token didn't even have `repo:status` permission. I swore I had that checked.

So I just 🔥d it and created a new one. But I'm still having issues :/

**Comment by kankaristo** [comment]
Is it still saying "API rate limit exceeded"? Does changing branches help?

You can also try `console.log(uri)` (after `atom-branch-status.coffee:83`) and trying to copy-paste that to a browser to see what you get back.

While you're there, you can also try commenting out `'If-None-Match': ifNoneMatch` (row 93) to see if that's causing problems?

**Comment by maddox** [comment]
> Is it still saying "API rate limit exceeded"? Does changing branches help?

yes, no. I restarted the app as well.

GitHub is also still saying `never used` for my token.

**Comment by maddox** [comment]
> You can also try console.log(uri) (after atom-branch-status.coffee:83) and trying to copy-paste that to a browser to see what you get back.

> https://api.github.com/repos/github/reponame/statuses/master

Which actually returns:

```json
{
  "message": "API rate limit exceeded for IPADDRESS. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

> While you're there, you can also try commenting out 'If-None-Match': ifNoneMatch (row 93) to see if that's causing problems?

This didn't change anything.

**Comment by maddox** [comment]
So, there was no token on that URL, I'll try to figure out why it's not seeing the token.

**Comment by kankaristo** [comment]
Huh, try printing the token from `getToken()`?

The token should be appended to the URI, unless it's empty (or null):
```coffee
# GitHub API address to poll (add token, if one is specified in settings)
uri = "https://api.github.com/repos/#{nameWithOwner}/statuses/#{ref}"
uri += "?access_token=#{token}" if token
```

**Comment by kankaristo** [comment]
And all `getToken()` does is:
```coffee
getToken = ->
  atom.config.get("branch-status.personalAccessToken")
```

**Comment by maddox** [comment]
It's def returning `undefined`. So is:

```coffeescript
atom.config.get("branch-status.personalAccessToken")
```

Looking into why now.

**Comment by maddox** [comment]
This seems crazy. All of the config logic looks perfectly fine. :/

**Comment by kankaristo** [comment]
The package used to be named `atom-branch-status` at some point, does this return anything?
```coffee
console.log(atom.config.get("atom-branch-status.personalAccessToken"))
```

What about manually setting the value?
```coffee
atom.config.set("branch-status.personalAccessToken", "new value")
console.log(atom.config.get("branch-status.personalAccessToken"))
```

**Comment by maddox** [comment]
> The package used to be named atom-branch-status at some point, does this return anything?

That did it!

**Comment by kankaristo** [comment]
That's really weird... Is the old name still lingering in the package somehow? Could this be an Atom bug?

**Comment by maddox** [comment]
In fact, the namespace everywhere else is still `atom-branch-status`, why isn't the config settings using it?

**Comment by maddox** [comment]
It's all over the place still.


screen shot 2015-06-11 at 11 03 40 am

If anything, all of this should be renamed probably.

**Comment by kankaristo** [comment]
The package's name was changed to `branch-status` a long time ago: https://github.com/nakajima/atom-branch-status/issues/2

I don't know if something is missing from the rename?

**Comment by maddox** [comment]
maybe open another PR to change everything out first, and then land this pr?

**Comment by maddox** [comment]
I still don't understand why the namespace is broken like this though, lol.

**Comment by kankaristo** [comment]
Can I do it in this PR?

Pretty much everything in master is broken for me, I can't even install the old package (https://github.com/nakajima/atom-branch-status/issues/9).

**Comment by maddox** [comment]
Seems legit, seeing that the point is getting this ready for `1.0`.

**Comment by maddox** [comment]
I still don't think fixing those keys is going to do anything regarding this configuration key.

/cc @kevinsawicki on some history around changing config keys

This package used to be named `atom-branch-status` but was renamed to `branch-status`. I had it installed originally when it had the old name. But now I have this fork installed (which has the new name). But it can't fetch settings with the new package name namespace. Bug?

**Comment by kankaristo** [comment]
I renamed it everywhere I could find (except for the repo name, obviously).

**Comment by maddox** [comment]
Just for testing sake, I fully uninstalled the package, and re-added it. And it's still broken.

I'll pull and try again, but I don't think those changes will effect anything.

Here's a thought, I have the package symlinked into `.atom/packages/atom-branch-status`. Is it pulling the name of the package from the path instead of the `package.json`?

**Comment by kankaristo** [comment]
Just to clarify: the package name was changed over a year ago (https://github.com/nakajima/atom-branch-status/issues/2).

I don't think the package had any configuration before this fork.

**Comment by maddox** [comment]
OK. I renamed the path to `branch-status` and it works perfectly now. I can see it reflected here too:

screen shot 2015-06-11 at 11 25 44 am

screen shot 2015-06-11 at 11 25 51 am

It's interesting that it's using the path name and not package name :/ Seems like a bug to me. But not one with this package.

**Comment by maddox** [comment]
@kankaristo I'm not seeing it go green now after pulling the last change. And see this error in the console:

>Failed to require the main module of 'branch-status' because it requires an incompatible native module.
Run `apm rebuild` in the package directory to resolve.

**Comment by kankaristo** [comment]
That's weird, it's working for me... Does `apm rebuild` fix it?

This fork removes the keytar dependency (which was breaking the install for me), so you may have to remove the `node_modules` directory inside the package and run `apm install`.

**Comment by maddox** [comment]
> That's weird, it's working for me... Does apm rebuild fix it?

nope.

> This fork removes the keytar dependency (which was breaking the install for me), so you may have to remove the node_modules directory inside the package and run apm install.

I looked in there and it wasn't in there. Just `request` and `atom-space-pen-views`.



> In other words, the currently released version may be installing keytar and old versions for some dependencies, so the dependencies need to be updated.

This shouldn't effect it since I've cloned your repo and switched to this branch.

**Comment by kankaristo** [comment]
I was doing `apm develop branch-status` and switching to this branch. I'm a novice with Atom packages, so I don't really know how development packages should be installed.

Running `apm install` inside the package seems to fix it, if I just do a plain clone of this fork. Is this done automatically if you install the (released) package in Atom, or is something broken in my fork?

I also have no idea if some of the packages are deprecated, use old versions, etc. I don't think this package needs `atom-space-pen-views`, should I use jQuery instead?

**Comment by maddox** [comment]
There's no `jquery` in atom anymore I don't think. Why is `atom-space-pen-views` used?

**Comment by maddox** [comment]
I'm not sure what's happening. I'm not that familiar either, heh. I'm just symlinking the cloned repo into `.atom/packages`

**Comment by kankaristo** [comment]
Does `apm install` fix it for you? I think this is done automatically for packages installed through `apm`.

The actual views aren't used, but `atom-space-pen-views` uses `space-pen`, which uses jQuery. This is how the package was originally implemented, but I think it could just use jQuery directly.

It's used to get the branch label from the status bar. I don't know if jQuery is considered deprecated in Atom or if there's a better way of doing this. I mostly just wanted to get the existing implementation working again.

**Comment by maddox** [comment]
> Does running apm install in the package dir fix it for you? I think this is done automatically for packages installed through apm.

Nope.

> The actual views aren't used, but atom-space-pen-views uses space-pen, which uses jQuery. This is how the package was originally implemented, but I think it could just use jQuery directly.

Certainly there's a better way to use selectors or fetch dom elements with already included tools in Atom lib right? Seems like including jquery is a hell of a dep to add.

> It's used to get the branch label from the status bar. I don't know if jQuery is considered deprecated in Atom or if there's a better way of doing this. I mostly just wanted to get the existing implementation working again.

Yeah, I hear ya.

**Comment by maddox** [comment]
Hmmm, I guess the 1.0 upgrade suggestions specifically say to use this:

>If you use any class from require 'atom' with a $ or View in the name, add the atom-space-pen-views module to your package’s package.json file’s dependencies:

**Comment by kankaristo** [comment]
Yep, the original `$ = require 'atom'` wasn't working anymore.

**Comment by kankaristo** [comment]
I guess the package could use [status-bar](https://github.com/atom/status-bar) as a dependency and:
- use `getRightTiles()` to get the "tiles" on the right hand side
- find the branch label tile
- use `getItem()` to get the branch label element?

The label could be cached so it doesn't need to be retrieved again and again on every poll (which happens every 5 seconds).

What do you think about merging this first (since it should be 1.0 compatible), and then creating another pull request for removing the `atom-space-pen-views` dependency? The changes in this PR are already pretty huge.

**Comment by maddox** [comment]
Yeah, I just wish it worked for me :/

Let me stop doing the weird symlinking and try the `apm develop` command instead.

**Comment by kankaristo** [comment]
Cloning the repo and running `apm install` also works for me (and I'm also symlinking from `~/.atom/packages/branch-status` to `~/github/branch-status`).

I don't know what's wrong with the dependencies on your end... :/

Does it even say *which* native module is incompatible?

**Comment by maddox** [comment]
Let's just merge it. What could happen. lol. The current version is broken as it is.

Can you bump the version to `0.8.0` first?

**Comment by maddox** [comment]
Is there no longer a secure place to put that token? Because any other package could actually fetch it and use it. Also, it persists even after uninstalling the package. I guess that's why its important to pick the right perms for the token though.

**Comment by kankaristo** [comment]
Doesn't `apm publish minor` do that automatically?

> Is there no longer a secure place to put that token? Because any other package could actually fetch it and use it. Also, it persists even after uninstalling the package. I guess that's why its important to pick the right perms for the token though.

I don't know if there's a better way of doing it, the old `keytar` way wasn't working for me (even after upgrading to a newer version, which actually installed).

I think a token in the package settings is the same way that [sync-settings](https://atom.io/packages/sync-settings) and [gist-it](https://atom.io/packages/gist-it) do it. Those both use gists instead of the GitHub API, but I'm not aware of any other (community) package that does something like this.

**Comment by maddox** [comment]
> Doesn't apm publish minor do that automatically?

Told you I was unfamiliar.

> I don't know if there's a better way of doing it, the old keytar way wasn't working for me (even after upgrading to a newer version, which actually installed).

We can just make a large note regarding security in the README. I'll toss something in after we merge.

**Comment by maddox** [comment]
Published!

**Comment by kankaristo** [comment]
Great, thanks! :+1:

**Comment by maddox** [comment]
Thanks for getting this back on track!

**Pull request merged**
